---

- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - name: Restart Dock
      ansible.builtin.command:
        cmd: killall Dock
      when: configure_dock
      tags: ['dock']
      changed_when: false

    - name: Applications | Configure Finder
      ansible.builtin.include_tasks: tasks/finder.yml
      tags: ['config', 'finder']

    - name: Applications | Photos | Prevent Photos from opening automatically when devices are plugged in
      community.general.osx_defaults:
        domain: com.apple.ImageCapture
        key: disableHotPlug
        type: bool
        value: true
        state: present
      tags: ['config', 'photos']

    - name: Privacy | Feedback Assistant - Turn off Feedback Assistant data auto-gathering
      community.general.osx_defaults:
        domain: com.apple.appleseed.FeedbackAssistant
        key: Autogather
        type: bool
        value: false
        state: present
      tags: ['config', 'privacy']

    - name: Privacy | Advertising - Disable Personalized Ads
      community.general.osx_defaults:
        domain: com.apple.AdLib
        key: allowApplePersonalizedAdvertising
        type: int
        value: 0
        state: present
      tags: ['config', 'privacy']

    - name: Security | Software Updates | Check for updates each day
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: ScheduleFrequency
        type: int
        value: 1
        state: present
      tags: ['config', 'security']

    - name: VS Code | Install extensions
      ansible.builtin.command: "code --install-extension {{ item }}"
      with_items: "{{ vscode_extensions }}"
      register: result
      changed_when: "'already installed' not in result.stdout"
      tags: ['config', 'vscode']
