---
- name: Screenshots | Make sure folder exists
  ansible.builtin.command: "mkdir -p ~/Screenshots"
  changed_when: false
  tags: ["config", "screenshots"]

- name: Screenshots | Location
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "~/Screenshots"
    state: present
  tags: ["config", "screenshots"]
